name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'
      - name: Build mobile with Gradle
        run: ./gradlew clean && ./gradlew assembleDebug
      - uses: actions/upload-artifact@v4
        with:
          name: mobile-debug.apk
          path: mobile/build/outputs/apk/debug/mobile-debug.apk
      - name: Build wear with Gradle
        run: ./gradlew clean && ./gradlew :wear:assembleDebug
      - uses: actions/upload-artifact@v4
        with:
          name: wear-debug.apk
          path: wear/build/outputs/apk/debug/wear-debug.apk
