name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: '11'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build mobile with Gradle
      run: ./gradlew clean && ./gradlew assembleDebug
    - uses: actions/upload-artifact@v2
      with:
        name: mobile-debug.apk
        path: mobile/build/outputs/apk/debug/mobile-debug.apk
    - name: Build wear with Gradle
      run: ./gradlew clean && ./gradlew :mobile:assembleDebug
    - uses: actions/upload-artifact@v2
      with:
        name: wear-debug.apk
        path: wear/build/outputs/apk/debug/wear-debug.apk
